name: pos
description: POS.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  cached_network_image: ^3.1.0
  cupertino_icons: ^1.0.2
  dotted_border: ^2.0.0+1
  expandable_page_view: ^1.0.5
  flutter:
    sdk: flutter
  flutter_slidable: ^1.1.0
  flutter_svg: ^0.22.0
  image_picker: ^0.8.4+4
  provider: ^5.0.0
  readmore: ^2.1.0
  shimmer: ^2.0.0
  # hive database
  hive: ^2.0.5
  hive_flutter: ^1.1.0
  path_provider: ^2.0.8
  # local notification
  flutter_local_notifications: ^9.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^1.7.2
  # hive database generator
  build_runner:
  hive_generator:

flutter:
  uses-material-design: true

  assets:
    - assets/images/
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
